### ISSUE TITLE
Dont see AddQueryRequestInterceptor on IServicesCollection

### ISSUE THREAD

**Issue by fazalfarruq** [lucasphi/Marshmallow.HotChocolate#19]
Hi All,

I am using .Net5 and HotChocolate 11. However when configuring my services I am not able to add **AddQueryRequestInterceptor** as it is not available on IServiceCollection. Is there some package that I am missing or need to add it? Please adivse.
Thanks.

**Comment by lucasphi** [comment]
Hey!

Please check the HotChocolate migration guide from version 10 to 11 https://chillicream.com/docs/hotchocolate/api-reference/migrate-from-10-to-11#request-interceptor
It seems that `AddQueryRequestInterceptor` was removed from the lib and renamed `AddHttpRequestInterceptor`

Please note that the current version of Marshmallow was not tested with hotchocolate 11. Also, I think it is worth mentioning that I believe version 11 of hotcholate does this natively https://chillicream.com/docs/hotchocolate/integrations/entity-framework, though I have not used version 11 myself to confirm.

**Comment by fazalfarruq** [comment]
I resolved this by using IResolverContext context
